title: Tamilarasu Arunachalam
description: "Documenting my developer journey: unpacking the how, what, and why behind the technical situations I tackle every day."
author: Tamilarasu Arunachalam
email: contact@yourdomain.com
baseurl: "" 
url: "https://tamilarasu.blog"
twitter_username: tamilarasu_av
github_username:  tamilarasu-arunachalam

# Build settings
markdown: kramdown
theme: minima
permalink: /:title.html
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# SEO Schema Advanced
google_search_console: 
google_analytics: G-NRDWJ8N6VV
facebook:
  app_id: 
  publisher: 
twitter:
  username: tamilarasu_av
  card: summary_large_image

# Cusdis Comments
cusdis_app_id: "c273ece9-1cf0-4c6e-aaca-9aa59564a335"
