backend:
  name: github
  repo: tamilarasu-arunachalam/blogs
  branch: master
  base_url: https://sveltia-cms-auth.tamilarasu-arunachalam.workers.dev/
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Meta Description", name: "description", widget: "text", required: false}
      - label: "Keywords"
        name: "keywords"
        widget: "list"
        required: false
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Dataverse", "Power Automate", "Dynamics 365 CRM", "Power Platform", "Azure Active Directory"]
        required: false
      - {label: "Body", name: "body", widget: "markdown"}